apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: mittal0706/flask_app:4
        ports:
        - containerPort: 5000
 
---

apiVersion: 3
kind: Service
metadata:
  name: flask-app-service
spec:
  type: LoadBalancer
  selector:
    app: flsk-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 31000
