apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: NodePort
  selector:
    app: flsk-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 31000
